#!/usr/bin/env python

VMANAGE = '[VMANGE FQDN or IP ADDRESS]'
USER = '[VMANAGE USERNAME with ACCESS to APIs]'
PASS = '[VMANAGE PASSWORD with ACCESS to APIs]'
ROUTER = '[ROUTERID as SEEN by VMANAGE]'
UMBORGID = '[UMBRELLA ORGANIZATION ID]'
UMBMGMTKEY = '[UMBRELLA MANAGEMENT API KEY]'
UMBMGMTSEC = '[UMBRELLA MANAGEMENT API SECRET]'
UMBDEVKEY = '[UMBRELLA NETWORK DEVICES API KEY]'
UMBDEVSEC = '[UMBRELLA NETWORK DEVICES API SECRET]'